# Generated by Django 5.0.4 on 2024-05-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestride', '0002_rename_user_id_requests_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name_plural': 'Requests'},
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterModelTable(
            name='requests',
            table='Requests',
        ),
    ]
