# Generated by Django 5.0.4 on 2024-05-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestride', '0003_alter_requests_options_rename_user_requests_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='user_id',
            new_name='user',
        ),
    ]
