# Generated by Django 5.0.4 on 2024-06-23 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestride', '0005_requests_status'),
        ('signup', '0003_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='matched_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='signup.users'),
        ),
    ]
