# Generated by Django 5.0.4 on 2024-07-06 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestride', '0006_requests_matched_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
